// 由 scripts/gen-cities.mjs 从 data/cities/pension.json 生成，不要手改。
import type { PensionRegion } from "./params";

/** 各省（及单独公布的城市）最新养老金计发基数（元/月）。id 为省 id 或城市 id。 */
export const PENSION_REGIONS: PensionRegion[] = [
  {"id":"beijing","name":"北京","provinceId":"beijing","base":{"year":2025,"value":12049}},
  {"id":"shanghai","name":"上海","provinceId":"shanghai","base":{"year":2026,"value":12577}},
  {"id":"tianjin","name":"天津","provinceId":"tianjin","base":{"year":2025,"value":9417}},
  {"id":"chongqing","name":"重庆","provinceId":"chongqing","base":{"year":2025,"value":8240}},
  {"id":"hebei","name":"河北","provinceId":"hebei","base":{"year":2025,"value":7410}},
  {"id":"shanxi","name":"山西","provinceId":"shanxi","base":{"year":2025,"value":7253},"note":"来源置信度低"},
  {"id":"neimenggu","name":"内蒙古","provinceId":"neimenggu","base":{"year":2026,"value":8430}},
  {"id":"liaoning","name":"辽宁（其他地区）","provinceId":"liaoning","base":{"year":2025,"value":7346}},
  {"id":"jilin","name":"吉林（其他地区）","provinceId":"jilin","base":{"year":2025,"value":7322.08}},
  {"id":"heilongjiang","name":"黑龙江","provinceId":"heilongjiang","base":{"year":2026,"value":7705}},
  {"id":"jiangsu","name":"江苏","provinceId":"jiangsu","base":{"year":2025,"value":8917}},
  {"id":"zhejiang","name":"浙江","provinceId":"zhejiang","base":{"year":2025,"value":8433}},
  {"id":"anhui","name":"安徽","provinceId":"anhui","base":{"year":2025,"value":7999}},
  {"id":"fujian","name":"福建","provinceId":"fujian","base":{"year":2025,"value":7932}},
  {"id":"jiangxi","name":"江西","provinceId":"jiangxi","base":{"year":2025,"value":7054}},
  {"id":"shandong","name":"山东（其他地区）","provinceId":"shandong","base":{"year":2025,"value":7831}},
  {"id":"henan","name":"河南","provinceId":"henan","base":{"year":2025,"value":6738}},
  {"id":"hubei","name":"湖北（其他地区）","provinceId":"hubei","base":{"year":2025,"value":7300},"note":"湖北未全省统一，武汉以外地区按 7300 估算"},
  {"id":"hunan","name":"湖南","provinceId":"hunan","base":{"year":2025,"value":7694}},
  {"id":"guangdong","name":"广东（其他地区）","provinceId":"guangdong","base":{"year":2025,"value":9493}},
  {"id":"guangxi","name":"广西","provinceId":"guangxi","base":{"year":2025,"value":6983}},
  {"id":"hainan","name":"海南","provinceId":"hainan","base":{"year":2025,"value":8188}},
  {"id":"sichuan","name":"四川","provinceId":"sichuan","base":{"year":2025,"value":8462},"note":"来源置信度低"},
  {"id":"guizhou","name":"贵州","provinceId":"guizhou","base":{"year":2026,"value":7376.75}},
  {"id":"yunnan","name":"云南","provinceId":"yunnan","base":{"year":2025,"value":8265}},
  {"id":"xizang","name":"西藏","provinceId":"xizang","base":{"year":2026,"value":11954}},
  {"id":"shaanxi","name":"陕西","provinceId":"shaanxi","base":{"year":2025,"value":7881}},
  {"id":"gansu","name":"甘肃","provinceId":"gansu","base":{"year":2025,"value":7746}},
  {"id":"qinghai","name":"青海","provinceId":"qinghai","base":{"year":2025,"value":9056}},
  {"id":"ningxia","name":"宁夏","provinceId":"ningxia","base":{"year":2025,"value":8366}},
  {"id":"xinjiang","name":"新疆","provinceId":"xinjiang","base":{"year":2025,"value":8448},"note":"来源置信度低"},
  {"id":"shenzhen","name":"深圳","provinceId":"guangdong","base":{"year":2025,"value":11293}},
  {"id":"shenyang","name":"沈阳","provinceId":"liaoning","base":{"year":2025,"value":8390}},
  {"id":"dalian","name":"大连","provinceId":"liaoning","base":{"year":2025,"value":8956}},
  {"id":"changchun","name":"长春","provinceId":"jilin","base":{"year":2025,"value":7978.25}},
  {"id":"wuhan","name":"武汉","provinceId":"hubei","base":{"year":2025,"value":9112}},
  {"id":"qingdao","name":"青岛","provinceId":"shandong","base":{"year":2025,"value":9010},"note":"来源置信度低"},
  {"id":"heze","name":"菏泽","provinceId":"shandong","base":{"year":2025,"value":7506}},
];
